version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-8.0.44
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 20112000
      MYSQL_DATABASE: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
