spring:
  application:
    name: NeoNHS

  datasource:
    url: jdbc:mysql://localhost:3306/neonhs_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${REDIS_HOST}
      port: 16079
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: false
      timeout: 60000
  mail:
    username: phamminhkiet24@gmail.com
    password: ${GOOGLE_MAIL_PASSWORD}

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yand0c2lnbmluZ3B1cnBvc2Vz
    expiration-ms: 86400000  # 24 hours
  fe-url: http://localhost:3000

google-auth:
  client-id: ${GOOGLE_AUTH_CLIENT_ID}
  client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
