spring:
  application:
    name: NeoNHS

  datasource:
    url: jdbc:mysql://localhost:3307/neonhs_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: 20112000
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

# JWT Configuration
app:
  jwt:
    secret: dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yand0c2lnbmluZ3B1cnBvc2Vz
    expiration-ms: 86400000  # 24 hours

google-auth:
  client-id: 755323177378-11nm4ungk8le19dtj6a0mlqfdiknhiot.apps.googleusercontent.com
  client-secret: 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
